# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import yolo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(help_text='What?', max_length=100)),
                ('where', models.CharField(blank=True, help_text='Where?', max_length=50, validators=[yolo.models.lnglat_validator])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag_set', models.ManyToManyField(blank=True, to='yolo.Tag')),
            ],
        ),
    ]
