# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0002_auto_20180421_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yolo',
            old_name='Image',
            new_name='image',
        ),
    ]
