# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import yolo.models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0003_auto_20180424_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yolo',
            name='where',
            field=models.CharField(blank=True, help_text='Do you know the location for this yolo?', max_length=50, validators=[yolo.models.lnglat_validator]),
        ),
    ]
