# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0008_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='who',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='who',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='yolo.Comment'),
        ),
    ]
