# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import yolo.models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0009_auto_20180713_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=50, validators=[yolo.models.lnglat_validator]),
        ),
    ]
