# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0010_post_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='location',
            new_name='latlng',
        ),
    ]
