# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 13:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import din.models

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yolo', '0004_auto_20180522_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Din',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(blank=True, max_length=50, validators=[din.models.lnglat_validator])),
                ('when', models.DateField(blank=True, verbose_name='objective due date')),
                ('note', models.TextField(blank=True, verbose_name='additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('what', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yolo.Yolo')),
                ('who', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
