# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 06:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yolo', '0004_auto_20180522_2215'),
        ('din', '0003_auto_20180525_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='din',
            options={'ordering': ['-id']},
        ),
        migrations.AlterUniqueTogether(
            name='din',
            unique_together=set([('what', 'who')]),
        ),
    ]
