# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('din', '0004_auto_20180531_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='din',
            name='where',
        ),
        migrations.AlterField(
            model_name='din',
            name='what',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yolo.Yolo'),
        ),
    ]
