# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('din', '0005_auto_20180615_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='write down your current thoughts, plan or contributing opinions here')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('what', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='din.Din')),
            ],
        ),
    ]
