# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('din', '0006_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='din',
            name='note',
        ),
        migrations.AddField(
            model_name='din',
            name='determination',
            field=models.TextField(blank=True, verbose_name='Your First thoughts'),
        ),
        migrations.AddField(
            model_name='log',
            name='type',
            field=models.CharField(choices=[('s', 'schedule'), ('p', 'preparations'), ('r', 'reference url'), ('c', 'completion & contribution'), ('n', 'social network')], default='p', max_length=1),
            preserve_default=False,
        ),
    ]
