# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('din', '0007_auto_20180620_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='din',
            name='determination',
        ),
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(choices=[('d', 'determination'), ('s', 'schedule'), ('p', 'preparations'), ('r', 'reference url'), ('c', 'completion & contribution')], max_length=1),
        ),
    ]
